# Generated by Django 5.2.13 on 2026-04-24 15:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Název')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL slug')),
                ('perex', models.TextField(max_length=400, verbose_name='Perex')),
                ('content', models.TextField(verbose_name='Obsah')),
                ('author', models.CharField(max_length=100, verbose_name='Autor')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Upraveno')),
            ],
            options={
                'verbose_name': 'Článek',
                'verbose_name_plural': 'Články',
                'ordering': ['-created_at'],
            },
        ),
    ]
